Update patch set 2
Patch Set 2:

The build failed because tag 4.1.0 already exixt, I found this in the log 

on-boarding 4.1.0
INFO: Running merge, pushing tag
Warning: Permanently added '[gerrit.acumos.org]:29418,[52.32.212.59]:29418' (ECDSA) to the list of known hosts.
To ssh://gerrit.acumos.org:29418/on-boarding
 ! [rejected]        4.1.0 -> 4.1.0 (already exists)
error: failed to push some refs to 'ssh://acumos-release@gerrit.acumos.org:29418/on-boarding'
hint: Updates were rejected because the tag already exists in the remote.
Build step 'Execute shell' marked build as failure

Patch-set: 2